import React from 'react';
import {
  ChartBarIcon,
  UserGroupIcon,
  DocumentTextIcon,
  CalendarIcon,
  CheckCircleIcon,
  CurrencyDollarIcon,
  BellIcon,
  CogIcon,
  ChartPieIcon,
  ClockIcon,
  GlobeAltIcon,
  EnvelopeIcon,
  PhoneIcon,
  MapPinIcon,
  DocumentIcon,
  FolderIcon,
  ShoppingCartIcon,
  TruckIcon,
  WrenchScrewdriverIcon,
  ComputerDesktopIcon,
  ServerIcon,
  ShieldCheckIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  StarIcon,
  HeartIcon,
  FireIcon,
  BoltIcon,
  CloudIcon,
  SunIcon,
  MoonIcon,
} from '@heroicons/react/24/outline';

export interface WidgetConfig {
  id: string;
  type: string;
  title: string;
  description: string;
  icon: React.ComponentType<any>;
  defaultSize: { width: number; height: number };
  minSize: { width: number; height: number };
  maxSize: { width: number; height: number };
  configurable: boolean;
  category: string;
}

export const availableWidgets: WidgetConfig[] = [
  // Analytics Widgets
  {
    id: 'stats-cards',
    type: 'stats-cards',
    title: 'Statistics Cards',
    description: 'Display key metrics and statistics',
    icon: ChartBarIcon,
    defaultSize: { width: 24, height: 8 },
    minSize: { width: 16, height: 6 },
    maxSize: { width: 32, height: 12 },
    configurable: true,
    category: 'Analytics',
  },
  {
    id: 'revenue-chart',
    type: 'revenue-chart',
    title: 'Revenue Chart',
    description: 'Visualize revenue trends and data',
    icon: ChartPieIcon,
    defaultSize: { width: 16, height: 12 },
    minSize: { width: 12, height: 8 },
    maxSize: { width: 24, height: 16 },
    configurable: true,
    category: 'Analytics',
  },
  {
    id: 'performance-metrics',
    type: 'performance-metrics',
    title: 'Performance Metrics',
    description: 'Track system and business performance',
    icon: BoltIcon,
    defaultSize: { width: 12, height: 8 },
    minSize: { width: 8, height: 6 },
    maxSize: { width: 20, height: 12 },
    configurable: true,
    category: 'Analytics',
  },
  {
    id: 'conversion-funnel',
    type: 'conversion-funnel',
    title: 'Conversion Funnel',
    description: 'Track customer conversion rates',
    icon: FireIcon,
    defaultSize: { width: 10, height: 12 },
    minSize: { width: 6, height: 8 },
    maxSize: { width: 18, height: 16 },
    configurable: true,
    category: 'Analytics',
  },

  // Productivity Widgets
  {
    id: 'tasks-widget',
    type: 'tasks-widget',
    title: 'Tasks Overview',
    description: 'Manage and view task progress',
    icon: CheckCircleIcon,
    defaultSize: { width: 8, height: 12 },
    minSize: { width: 6, height: 8 },
    maxSize: { width: 16, height: 20 },
    configurable: true,
    category: 'Productivity',
  },
  {
    id: 'projects-overview',
    type: 'projects-overview',
    title: 'Projects Overview',
    description: 'Track project status and progress',
    icon: DocumentTextIcon,
    defaultSize: { width: 12, height: 10 },
    minSize: { width: 8, height: 8 },
    maxSize: { width: 20, height: 16 },
    configurable: true,
    category: 'Productivity',
  },
  {
    id: 'time-tracking',
    type: 'time-tracking',
    title: 'Time Tracking',
    description: 'Monitor time spent on tasks and projects',
    icon: ClockIcon,
    defaultSize: { width: 10, height: 8 },
    minSize: { width: 6, height: 6 },
    maxSize: { width: 16, height: 12 },
    configurable: true,
    category: 'Productivity',
  },
  {
    id: 'goals-progress',
    type: 'goals-progress',
    title: 'Goals Progress',
    description: 'Track progress towards business goals',
    icon: StarIcon,
    defaultSize: { width: 8, height: 10 },
    minSize: { width: 4, height: 6 },
    maxSize: { width: 14, height: 16 },
    configurable: true,
    category: 'Productivity',
  },

  // Communication Widgets
  {
    id: 'email-overview',
    type: 'email-overview',
    title: 'Email Overview',
    description: 'Monitor email activity and inbox status',
    icon: EnvelopeIcon,
    defaultSize: { width: 10, height: 8 },
    minSize: { width: 6, height: 6 },
    maxSize: { width: 16, height: 12 },
    configurable: true,
    category: 'Communication',
  },
  {
    id: 'chat-activity',
    type: 'chat-activity',
    title: 'Chat Activity',
    description: 'View recent chat messages and conversations',
    icon: PhoneIcon,
    defaultSize: { width: 8, height: 10 },
    minSize: { width: 4, height: 6 },
    maxSize: { width: 14, height: 16 },
    configurable: true,
    category: 'Communication',
  },
  {
    id: 'meeting-schedule',
    type: 'meeting-schedule',
    title: 'Meeting Schedule',
    description: 'View upcoming meetings and appointments',
    icon: CalendarIcon,
    defaultSize: { width: 10, height: 8 },
    minSize: { width: 6, height: 6 },
    maxSize: { width: 16, height: 12 },
    configurable: true,
    category: 'Communication',
  },

  // Monitoring Widgets
  {
    id: 'recent-activity',
    type: 'recent-activity',
    title: 'Recent Activity',
    description: 'Show latest system activities',
    icon: ClockIcon,
    defaultSize: { width: 12, height: 12 },
    minSize: { width: 8, height: 8 },
    maxSize: { width: 20, height: 16 },
    configurable: true,
    category: 'Monitoring',
  },
  {
    id: 'notifications-widget',
    type: 'notifications-widget',
    title: 'Notifications',
    description: 'Display system notifications and alerts',
    icon: BellIcon,
    defaultSize: { width: 8, height: 12 },
    minSize: { width: 4, height: 8 },
    maxSize: { width: 16, height: 20 },
    configurable: true,
    category: 'Monitoring',
  },
  {
    id: 'system-health',
    type: 'system-health',
    title: 'System Health',
    description: 'Monitor system performance and status',
    icon: HeartIcon,
    defaultSize: { width: 10, height: 8 },
    minSize: { width: 6, height: 6 },
    maxSize: { width: 16, height: 12 },
    configurable: true,
    category: 'Monitoring',
  },
  {
    id: 'error-logs',
    type: 'error-logs',
    title: 'Error Logs',
    description: 'View system errors and warnings',
    icon: ExclamationTriangleIcon,
    defaultSize: { width: 8, height: 10 },
    minSize: { width: 4, height: 6 },
    maxSize: { width: 14, height: 16 },
    configurable: true,
    category: 'Monitoring',
  },

  // Navigation Widgets
  {
    id: 'quick-actions',
    type: 'quick-actions',
    title: 'Quick Actions',
    description: 'Common actions and shortcuts',
    icon: CogIcon,
    defaultSize: { width: 8, height: 8 },
    minSize: { width: 4, height: 4 },
    maxSize: { width: 16, height: 12 },
    configurable: true,
    category: 'Navigation',
  },
  {
    id: 'favorites',
    type: 'favorites',
    title: 'Favorites',
    description: 'Quick access to favorite pages and tools',
    icon: StarIcon,
    defaultSize: { width: 6, height: 8 },
    minSize: { width: 4, height: 6 },
    maxSize: { width: 12, height: 12 },
    configurable: true,
    category: 'Navigation',
  },

  // Team Widgets
  {
    id: 'team-overview',
    type: 'team-overview',
    title: 'Team Overview',
    description: 'View team members and status',
    icon: UserGroupIcon,
    defaultSize: { width: 12, height: 12 },
    minSize: { width: 8, height: 8 },
    maxSize: { width: 20, height: 16 },
    configurable: true,
    category: 'Team',
  },
  {
    id: 'team-availability',
    type: 'team-availability',
    title: 'Team Availability',
    description: 'Check team member availability and schedules',
    icon: CalendarIcon,
    defaultSize: { width: 10, height: 8 },
    minSize: { width: 6, height: 6 },
    maxSize: { width: 16, height: 12 },
    configurable: true,
    category: 'Team',
  },

  // Scheduling Widgets
  {
    id: 'calendar-widget',
    type: 'calendar-widget',
    title: 'Calendar',
    description: 'Display upcoming events and meetings',
    icon: CalendarIcon,
    defaultSize: { width: 12, height: 12 },
    minSize: { width: 8, height: 8 },
    maxSize: { width: 20, height: 16 },
    configurable: true,
    category: 'Scheduling',
  },
  {
    id: 'deadlines',
    type: 'deadlines',
    title: 'Deadlines',
    description: 'Track upcoming deadlines and due dates',
    icon: ClockIcon,
    defaultSize: { width: 8, height: 10 },
    minSize: { width: 4, height: 6 },
    maxSize: { width: 14, height: 16 },
    configurable: true,
    category: 'Scheduling',
  },

  // Finance Widgets
  {
    id: 'financial-overview',
    type: 'financial-overview',
    title: 'Financial Overview',
    description: 'Track financial metrics and trends',
    icon: CurrencyDollarIcon,
    defaultSize: { width: 12, height: 12 },
    minSize: { width: 8, height: 8 },
    maxSize: { width: 20, height: 16 },
    configurable: true,
    category: 'Finance',
  },
  {
    id: 'expense-tracker',
    type: 'expense-tracker',
    title: 'Expense Tracker',
    description: 'Monitor and categorize expenses',
    icon: ShoppingCartIcon,
    defaultSize: { width: 10, height: 8 },
    minSize: { width: 6, height: 6 },
    maxSize: { width: 16, height: 12 },
    configurable: true,
    category: 'Finance',
  },
  {
    id: 'budget-overview',
    type: 'budget-overview',
    title: 'Budget Overview',
    description: 'Track budget vs actual spending',
    icon: DocumentIcon,
    defaultSize: { width: 8, height: 10 },
    minSize: { width: 4, height: 6 },
    maxSize: { width: 14, height: 16 },
    configurable: true,
    category: 'Finance',
  },

  // Document Widgets
  {
    id: 'document-library',
    type: 'document-library',
    title: 'Document Library',
    description: 'Access and manage documents',
    icon: FolderIcon,
    defaultSize: { width: 10, height: 8 },
    minSize: { width: 6, height: 6 },
    maxSize: { width: 16, height: 12 },
    configurable: true,
    category: 'Documents',
  },
  {
    id: 'recent-documents',
    type: 'recent-documents',
    title: 'Recent Documents',
    description: 'View recently accessed documents',
    icon: DocumentIcon,
    defaultSize: { width: 8, height: 10 },
    minSize: { width: 4, height: 6 },
    maxSize: { width: 14, height: 16 },
    configurable: true,
    category: 'Documents',
  },

  // Operations Widgets
  {
    id: 'inventory-status',
    type: 'inventory-status',
    title: 'Inventory Status',
    description: 'Monitor inventory levels and stock',
    icon: TruckIcon,
    defaultSize: { width: 10, height: 8 },
    minSize: { width: 6, height: 6 },
    maxSize: { width: 16, height: 12 },
    configurable: true,
    category: 'Operations',
  },
  {
    id: 'maintenance-schedule',
    type: 'maintenance-schedule',
    title: 'Maintenance Schedule',
    description: 'Track equipment maintenance and repairs',
    icon: WrenchScrewdriverIcon,
    defaultSize: { width: 8, height: 10 },
    minSize: { width: 4, height: 6 },
    maxSize: { width: 14, height: 16 },
    configurable: true,
    category: 'Operations',
  },

  // IT Widgets
  {
    id: 'server-status',
    type: 'server-status',
    title: 'Server Status',
    description: 'Monitor server health and performance',
    icon: ServerIcon,
    defaultSize: { width: 10, height: 8 },
    minSize: { width: 6, height: 6 },
    maxSize: { width: 16, height: 12 },
    configurable: true,
    category: 'IT',
  },
  {
    id: 'backup-status',
    type: 'backup-status',
    title: 'Backup Status',
    description: 'Monitor backup processes and status',
    icon: CloudIcon,
    defaultSize: { width: 8, height: 10 },
    minSize: { width: 4, height: 6 },
    maxSize: { width: 14, height: 16 },
    configurable: true,
    category: 'IT',
  },
  {
    id: 'security-alerts',
    type: 'security-alerts',
    title: 'Security Alerts',
    description: 'Monitor security events and threats',
    icon: ShieldCheckIcon,
    defaultSize: { width: 8, height: 10 },
    minSize: { width: 4, height: 6 },
    maxSize: { width: 14, height: 16 },
    configurable: true,
    category: 'IT',
  },

  // Marketing Widgets
  {
    id: 'campaign-performance',
    type: 'campaign-performance',
    title: 'Campaign Performance',
    description: 'Track marketing campaign metrics',
    icon: GlobeAltIcon,
    defaultSize: { width: 12, height: 10 },
    minSize: { width: 8, height: 6 },
    maxSize: { width: 20, height: 14 },
    configurable: true,
    category: 'Marketing',
  },
  {
    id: 'social-media-feed',
    type: 'social-media-feed',
    title: 'Social Media Feed',
    description: 'Monitor social media activity',
    icon: GlobeAltIcon,
    defaultSize: { width: 10, height: 12 },
    minSize: { width: 6, height: 8 },
    maxSize: { width: 16, height: 18 },
    configurable: true,
    category: 'Marketing',
  },

  // Weather Widgets
  {
    id: 'weather-widget',
    type: 'weather-widget',
    title: 'Weather',
    description: 'Display current weather information',
    icon: SunIcon,
    defaultSize: { width: 6, height: 8 },
    minSize: { width: 4, height: 6 },
    maxSize: { width: 12, height: 12 },
    configurable: true,
    category: 'Weather',
  },

  // Custom Widgets
  {
    id: 'custom-html',
    type: 'custom-html',
    title: 'Custom HTML',
    description: 'Add custom HTML content',
    icon: DocumentTextIcon,
    defaultSize: { width: 8, height: 8 },
    minSize: { width: 4, height: 4 },
    maxSize: { width: 20, height: 20 },
    configurable: true,
    category: 'Custom',
  },
  {
    id: 'iframe-widget',
    type: 'iframe-widget',
    title: 'External Website',
    description: 'Embed external websites or tools',
    icon: GlobeAltIcon,
    defaultSize: { width: 12, height: 10 },
    minSize: { width: 8, height: 6 },
    maxSize: { width: 24, height: 20 },
    configurable: true,
    category: 'Custom',
  },
];

export const getWidgetByType = (type: string): WidgetConfig | undefined => {
  return availableWidgets.find(widget => widget.type === type);
};

export const getWidgetsByCategory = (category: string): WidgetConfig[] => {
  return availableWidgets.filter(widget => widget.category === category);
};

export const getAllCategories = (): string[] => {
  return [...new Set(availableWidgets.map(widget => widget.category))];
};
