import { MenuItem } from '../types/menu';

export const defaultMenu: MenuItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'dashboard',
    type: 'parent',
    visible: true,
    order: 1,
  },
  {
    id: 'communications',
    label: 'Communications',
    icon: 'mail',
    type: 'parent',
    visible: true,
    order: 2,
    children: [
      {
        id: 'email',
        label: 'Email',
        icon: 'mail',
        type: 'child',
        parentId: 'communications',
        moduleKey: 'email',
        visible: true,
        order: 1,
      },
      {
        id: 'chat',
        label: 'Chat/Messenger',
        icon: 'chat-bubble',
        type: 'child',
        parentId: 'communications',
        moduleKey: 'chat',
        visible: true,
        order: 2,
      },
    ],
  },
  {
    id: 'crm',
    label: 'CRM',
    icon: 'crm',
    type: 'parent',
    visible: true,
    order: 3,
    children: [
      {
        id: 'customers',
        label: 'Customers',
        icon: 'users',
        type: 'child',
        parentId: 'crm',
        moduleKey: 'customers',
        visible: true,
        order: 1,
      },
      {
        id: 'contractors',
        label: 'Contractors',
        icon: 'identification',
        type: 'child',
        parentId: 'crm',
        moduleKey: 'contractors',
        visible: true,
        order: 2,
      },
    ],
  },
  {
    id: 'projects',
    label: 'Projects',
    icon: 'projects',
    type: 'parent',
    visible: true,
    order: 4,
  },
  {
    id: 'calendar',
    label: 'Calendar',
    icon: 'calendar',
    type: 'parent',
    visible: true,
    order: 5,
  },
  {
    id: 'opportunities',
    label: 'Opportunities',
    icon: 'opportunities',
    type: 'parent',
    visible: true,
    order: 6,
    children: [
      {
        id: 'sales-pipeline',
        label: 'Sales Pipeline',
        icon: 'presentation-chart-line',
        type: 'child',
        parentId: 'opportunities',
        moduleKey: 'sales-pipeline',
        visible: true,
        order: 1,
      },
    ],
  },
  {
    id: 'document-hub',
    label: 'Document Hub',
    icon: 'documents',
    type: 'parent',
    visible: true,
    order: 7,
    children: [
      {
        id: 'library',
        label: 'Library',
        icon: 'book-open',
        type: 'child',
        parentId: 'document-hub',
        moduleKey: 'library',
        visible: true,
        order: 1,
      },
      {
        id: 'document-builder',
        label: 'Document Builder',
        icon: 'document-text',
        type: 'child',
        parentId: 'document-hub',
        moduleKey: 'document-builder',
        visible: true,
        order: 2,
      },
    ],
  },
  {
    id: 'tasks',
    label: 'Tasks',
    icon: 'tasks',
    type: 'parent',
    visible: true,
    order: 8,
  },
  {
    id: 'procurement',
    label: 'Procurement',
    icon: 'procurement',
    type: 'parent',
    visible: true,
    order: 9,
  },
  {
    id: 'users',
    label: 'Users & Roles',
    icon: 'users',
    type: 'parent',
    visible: true,
    order: 10,
    children: [
      {
        id: 'user-management',
        label: 'User Management',
        icon: 'users',
        type: 'child',
        parentId: 'users',
        moduleKey: 'user-management',
        visible: true,
        order: 1,
      },
      {
        id: 'permissions',
        label: 'Permissions',
        icon: 'key',
        type: 'child',
        parentId: 'users',
        moduleKey: 'permissions',
        visible: true,
        order: 2,
      },
    ],
  },
  {
    id: 'roles-permissions-matrix',
    label: 'Roles & Permissions Matrix',
    icon: 'key',
    type: 'parent',
    visible: true,
    order: 12,
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: 'settings',
    type: 'parent',
    visible: true,
    order: 11,
    children: [
      {
        id: 'general-settings',
        label: 'General Settings',
        icon: 'cog',
        type: 'child',
        parentId: 'settings',
        visible: true,
        order: 1,
      },
      {
        id: 'menu-builder',
        label: 'Menu Builder',
        icon: 'wrench',
        type: 'child',
        parentId: 'settings',
        visible: true,
        order: 2,
      },
      {
        id: 'modules',
        label: 'Modules',
        icon: 'puzzle-piece',
        type: 'child',
        parentId: 'settings',
        visible: true,
        order: 3,
      },
    ],
  },
  {
    id: 'support',
    label: 'Support',
    icon: 'support',
    type: 'parent',
    visible: true,
    order: 12,
    children: [
      {
        id: 'help',
        label: 'Help',
        icon: 'question-mark-circle',
        type: 'child',
        parentId: 'support',
        visible: true,
        order: 1,
      },
      {
        id: 'live-chat',
        label: 'Live Chat',
        icon: 'chat-bubble',
        type: 'child',
        parentId: 'support',
        visible: true,
        order: 2,
      },
      {
        id: 'knowledge-base',
        label: 'Knowledge Base',
        icon: 'book-open',
        type: 'child',
        parentId: 'support',
        visible: true,
        order: 3,
      },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    icon: 'finance',
    type: 'parent',
    visible: true,
    order: 13,
    children: [
      {
        id: 'invoicing',
        label: 'Invoicing',
        icon: 'currency-pound',
        type: 'child',
        parentId: 'finance',
        moduleKey: 'invoicing',
        visible: true,
        order: 1,
      },
      {
        id: 'accounting',
        label: 'Accounting & PAYE',
        icon: 'banknotes',
        type: 'child',
        parentId: 'finance',
        moduleKey: 'accounting',
        visible: true,
        order: 2,
      },
    ],
  },
  {
    id: 'hr',
    label: 'HR',
    icon: 'user-circle',
    type: 'parent',
    visible: true,
    order: 14,
  },
  {
    id: 'roadmap',
    label: 'Roadmap',
    icon: 'map',
    type: 'parent',
    visible: true,
    order: 15,
  },
  {
    id: 'changelog',
    label: 'Changelog',
    icon: 'arrow-path',
    type: 'parent',
    visible: true,
    order: 16,
  },
  {
    id: 'marketing',
    label: 'Marketing',
    icon: 'megaphone',
    type: 'parent',
    visible: true,
    order: 17,
  },
];
