name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to production
      run: echo "Deployment step - configure your deployment platform here"
      # Add your deployment steps here:
      # - For Vercel: use vercel/action
      # - For Netlify: use nwtgck/actions-netlify
      # - For AWS: use aws-actions/configure-aws-credentials
      # - For Docker: build and push to registry
